# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Display.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UE(object):
    def setupUi(self, UE):
        UE.setObjectName("UE")
        UE.resize(802, 479)
        self.centralwidget = QtWidgets.QWidget(UE)
        self.centralwidget.setObjectName("centralwidget")
        self.camera1 = QtWidgets.QLabel(self.centralwidget)
        self.camera1.setGeometry(QtCore.QRect(30, 20, 120, 90))
        self.camera1.setObjectName("camera1")
        self.camera2 = QtWidgets.QLabel(self.centralwidget)
        self.camera2.setGeometry(QtCore.QRect(190, 20, 120, 90))
        self.camera2.setObjectName("camera2")
        self.camera3 = QtWidgets.QLabel(self.centralwidget)
        self.camera3.setGeometry(QtCore.QRect(350, 20, 120, 90))
        self.camera3.setObjectName("camera3")
        self.camera4 = QtWidgets.QLabel(self.centralwidget)
        self.camera4.setGeometry(QtCore.QRect(30, 190, 120, 90))
        self.camera4.setObjectName("camera4")
        self.camera5 = QtWidgets.QLabel(self.centralwidget)
        self.camera5.setGeometry(QtCore.QRect(190, 190, 120, 90))
        self.camera5.setObjectName("camera5")
        self.camera6 = QtWidgets.QLabel(self.centralwidget)
        self.camera6.setGeometry(QtCore.QRect(350, 190, 120, 90))
        self.camera6.setObjectName("camera6")
        self.groupBox_classification = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_classification.setGeometry(QtCore.QRect(640, 40, 101, 111))
        self.groupBox_classification.setObjectName("groupBox_classification")
        self.two_class = QtWidgets.QRadioButton(self.groupBox_classification)
        self.two_class.setGeometry(QtCore.QRect(20, 20, 89, 21))
        self.two_class.setObjectName("two_class")
        self.three_class = QtWidgets.QRadioButton(self.groupBox_classification)
        self.three_class.setGeometry(QtCore.QRect(20, 50, 89, 16))
        self.three_class.setObjectName("three_class")
        self.four_class = QtWidgets.QRadioButton(self.groupBox_classification)
        self.four_class.setGeometry(QtCore.QRect(20, 80, 89, 16))
        self.four_class.setObjectName("four_class")
        self.device = QtWidgets.QLabel(self.centralwidget)
        self.device.setGeometry(QtCore.QRect(30, 350, 411, 31))
        self.device.setObjectName("device")
        self.model = QtWidgets.QLabel(self.centralwidget)
        self.model.setGeometry(QtCore.QRect(30, 390, 411, 31))
        self.model.setObjectName("model")
        self.groupBox_type = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_type.setGeometry(QtCore.QRect(500, 40, 121, 80))
        self.groupBox_type.setObjectName("groupBox_type")
        self.real_time = QtWidgets.QRadioButton(self.groupBox_type)
        self.real_time.setGeometry(QtCore.QRect(20, 20, 111, 16))
        self.real_time.setObjectName("real_time")
        self.local_file = QtWidgets.QRadioButton(self.groupBox_type)
        self.local_file.setGeometry(QtCore.QRect(20, 50, 111, 16))
        self.local_file.setObjectName("local_file")
        self.load_model = QtWidgets.QPushButton(self.centralwidget)
        self.load_model.setGeometry(QtCore.QRect(500, 160, 111, 31))
        self.load_model.setObjectName("load_model")
        self.load_file = QtWidgets.QPushButton(self.centralwidget)
        self.load_file.setGeometry(QtCore.QRect(500, 220, 111, 31))
        self.load_file.setObjectName("load_file")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(630, 160, 141, 241))
        self.textBrowser.setObjectName("textBrowser")
        self.Start = QtWidgets.QPushButton(self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(500, 280, 111, 31))
        self.Start.setObjectName("Start")
        self.Stop = QtWidgets.QPushButton(self.centralwidget)
        self.Stop.setGeometry(QtCore.QRect(500, 340, 111, 31))
        self.Stop.setObjectName("Stop")
        self.led1 = QtWidgets.QLabel(self.centralwidget)
        self.led1.setGeometry(QtCore.QRect(90, 130, 20, 20))
        self.led1.setObjectName("led1")
        self.led4 = QtWidgets.QLabel(self.centralwidget)
        self.led4.setGeometry(QtCore.QRect(90, 300, 20, 20))
        self.led4.setObjectName("led4")
        self.led2 = QtWidgets.QLabel(self.centralwidget)
        self.led2.setGeometry(QtCore.QRect(250, 130, 20, 20))
        self.led2.setObjectName("led2")
        self.led5 = QtWidgets.QLabel(self.centralwidget)
        self.led5.setGeometry(QtCore.QRect(250, 300, 20, 20))
        self.led5.setObjectName("led5")
        self.led3 = QtWidgets.QLabel(self.centralwidget)
        self.led3.setGeometry(QtCore.QRect(410, 130, 20, 20))
        self.led3.setObjectName("led3")
        self.led6 = QtWidgets.QLabel(self.centralwidget)
        self.led6.setGeometry(QtCore.QRect(410, 300, 20, 20))
        self.led6.setObjectName("led6")
        UE.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UE)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 23))
        self.menubar.setObjectName("menubar")
        UE.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UE)
        self.statusbar.setObjectName("statusbar")
        UE.setStatusBar(self.statusbar)

        self.retranslateUi(UE)
        QtCore.QMetaObject.connectSlotsByName(UE)

    def retranslateUi(self, UE):
        _translate = QtCore.QCoreApplication.translate
        UE.setWindowTitle(_translate("UE", "UE监控预警"))
        self.camera1.setText(_translate("UE", "camera1"))
        self.camera2.setText(_translate("UE", "camera2"))
        self.camera3.setText(_translate("UE", "camera3"))
        self.camera4.setText(_translate("UE", "camera4"))
        self.camera5.setText(_translate("UE", "camera5"))
        self.camera6.setText(_translate("UE", "camera6"))
        self.groupBox_classification.setTitle(_translate("UE", "分类方式"))
        self.two_class.setText(_translate("UE", "二分类"))
        self.three_class.setText(_translate("UE", "三分类"))
        self.four_class.setText(_translate("UE", "四分类"))
        self.device.setText(_translate("UE", "device"))
        self.model.setText(_translate("UE", "model"))
        self.groupBox_type.setTitle(_translate("UE", "监控模式"))
        self.real_time.setText(_translate("UE", "实时监测模式"))
        self.local_file.setText(_translate("UE", "本地文件模式"))
        self.load_model.setText(_translate("UE", "加载模型"))
        self.load_file.setText(_translate("UE", "本地文件"))
        self.textBrowser.setHtml(_translate("UE", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">使用说明：</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">1.选择监控模式：实时监测模式为在线实时监测，本地文件模式是选择本地视频文件测试；</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">2.选择分类方式：分类方式越多对动作的分类更为细致；</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">3.加载模型：加载C3D网络权重文件；</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">4.本地文件：当监控模式选择本地文件模式时，通过此选项选择本地视频文件；</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">5.开始监测：开始UE监控预警测试；</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">6.停止监测：停止UE监控预警测试。</span></p></body></html>"))
        self.Start.setText(_translate("UE", "开始监测"))
        self.Stop.setText(_translate("UE", "停止监测"))
        self.led1.setText(_translate("UE", "led1"))
        self.led4.setText(_translate("UE", "led4"))
        self.led2.setText(_translate("UE", "led2"))
        self.led5.setText(_translate("UE", "led5"))
        self.led3.setText(_translate("UE", "led3"))
        self.led6.setText(_translate("UE", "led6"))
